### ISSUE TITLE
Consider switching to munit instead of scalatest

### ISSUE THREAD

**Issue by ckipp01** [scala/hello-world.g8#60]
I use this repo pretty frequently to bootstrap minimal sbt projects, and I often recommend people struggling with setting up an sbt project to do the same. Today while using this again I had a thought about using Scalatest. In light of the announcement of [Scala Toolkit](https://virtuslab.com/blog/scala-toolkit-makes-scala-powerful-straight-out-of-the-box/) and the decision to use munit as the testing framework, I wonder if it makes sense to align this template with that.

I'm happy to pr this change.

**Comment by SethTisue** [comment]
Yes, I'd merge a PR that did that.

**Comment by ckipp01** [comment]
I see this repo doesn't even have tests, so I'm not 100% sure what I was thinking when I created this. I was maybe thinking about the Scala 3 one, but that one does have munit, so just ignore this.
